
        
<ScreenAdmin>:
    calendar: calendar
    manage_patient:manage_patient
    drop_down:drop_down.__self__
    DropDown:
        id:drop_down
        Button:
            text: 'Appointments'
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.appointment_list()
            canvas.before:
                                    
                Color:
                    rgba: 1, 1, 1, .2
                Line:
                    width:1
                    rectangle: (self.x,self.y-5, self.width, 0)
                                                         


        Button:
            text: 'View Payments'
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.select('#003300')
            canvas.before:
                                    
                Color:
                    rgba: 1, 1, 1, .2
                Line:
                    width:1
                    rectangle: (self.x,self.y-5, self.width, 0)
                                                       

        Button:
            text: 'View Bed Status'
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.allotment_list()
            canvas.before:
                                    
                Color:
                    rgba: 1, 1, 1, .2
                Line:
                    width:1
                    rectangle: (self.x,self.y-5, self.width, 0)
                                                       

        Button:
            text: 'Viwe Blood Bank'
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.blood_bank()

        Button:
            text: 'View Medicine '
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.pharm_list()
            canvas.before:
                                    
                Color:
                    rgba: 1, 1, 1, .2
                Line:
                    width:1
                    rectangle: (self.x,self.y-5, self.width, 0)
                                                       

        Button:
            text: 'VIew Operation'
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.report_list()
            canvas.before:
                                    
                Color:
                    rgba: 1, 1, 1, .2
                Line:
                    width:1
                    rectangle: (self.x,self.y-5, self.width, 0)
                                                       

        Button:
            text: 'View Birth Report'
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.report_list()
            canvas.before:
                                    
                Color:
                    rgba: 1, 1, 1, .2
                Line:
                    width:1
                    rectangle: (self.x,self.y-5, self.width, 0)
                                                       

        Button:
            text: 'View Death Report'
            background_normal:""
            background_color: rgba('#003300')
            background_down:'dark.png'
            font_size: 25
            size_hint:None,None
            size:self.texture_size
            on_release: root.report_list()
            canvas.before:
                                    
                Color:
                    rgba: 1, 1, 1, .2
                Line:
                    width:1
                    rectangle: (self.x,self.y-5, self.width, 0)
                                                       

    
    BoxLayout:
        orientation: 'vertical'
        padding: root.width*0.005,root.height*0.005
        canvas:
            Color:
                rgba:1,1,1,1
            Rectangle:
                pos: self.pos
                size: self.size
        ActionBar:
            pos_hint: {'top':1}
            ActionView:
                use_separator: True
                ActionPrevious:
                    title: 'Hospital Management System'
                    with_previous: False
                ActionButton:
                    text: "Admin's Panel"
                    background_down:'1,0,1,0'
                    
                ActionGroup:
                    text: 'Account' 
                    mode: 'spinner'
                    ActionButton:
                        text: 'Profile'
                        on_press:root.profile()
                    ActionButton:
                        text: 'Log Out'
                        on_press:root.manager.current='Login'


    
    


        BoxLayout:
            orientation:'horizontal'
            spacing:2
                
            BoxLayout:
                orientation:'vertical'
                size_hint:(None,None)
                size:300, self.parent.height  
                spacing:20
                
                BoxLayout:
                    orientation:'vertical'
                    
                    canvas:
                        Color:
                            rgba: rgba('#010c47')
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    ImageButton:
                                
                        source:'assets/hsign.png'  
                        size_hint:(None,None)
                        size:(200,80)
                        
                    Label:
                        text:""
                        size_hint_y:None
                        height:15
                        canvas.before:
                                
                            Color:
                                rgba: 1, 1, 1, .2
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                                                     

                            
                        

                    GridLayout:
                        cols :1
                        spacing:25
                        row_force_default: True
                        row_default_height: 20
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/computer.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"DashBoard"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.dashboard()

                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/group.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"Department"
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.department_list()


                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/doctor.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"Doctor"
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.doctor_list()
                                

                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/patient.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"Patient"
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.patient()

                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/nurse.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"Nurse"
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.nurse_list()

                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/prescription.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"Pharmascist"
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.pharm_list()
                        BoxLayout:
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/pencil.png'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"Labaratorist "
                                background_normal:""
                                background_down:'dark.png'
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.lab_list()

                        BoxLayout:
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/download1.jpg'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"Accountant"
                                background_down:'dark.png'
                                background_normal:""
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.accountant_list()

                        BoxLayout:
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/list.png'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"Monitor Hospital"
                                background_down:'dark.png'
                                background_normal:""
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_release: 
                                    if not root.state:drop_down.open(self); root.state = True
                                    else:drop_down.dismiss(); root.state = False
                                                        


                            
                                

                        BoxLayout:
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/gamepad.png'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"Settings"
                                background_down:'dark.png'
                                background_normal:""
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                               

                        BoxLayout:
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/clipboard.png'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"Attendance"
                                background_normal:""
                                background_down:'dark.png'
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size

                        BoxLayout:
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/boy.png'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"Profile"
                                background_normal:""
                                background_down:'dark.png'
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint:None,None
                                size:self.texture_size
                                on_press:root.profile()

                        




       

  
                            
                                          
##########         """ dynamic part begins here"""    ######################

                                
         
            BoxLayout:
                    
                BoxLayout:
                    orientation:'vertical'
                    
                    BoxLayout:
                        canvas:
                            Color:
                                rgba: 0, 0, 0, .9
                            Line:
                                width: 2.
                                rectangle: (self.x, self.y, self.width, self.height)
                        BoxLayout:
                            id:manage_patient
                            orientation: 'vertical'
                            spacing:10
                            padding:self.height*0.02, self.width*0.02

                            BoxLayout:
                                orientation:'horizontal'
                                spacing:10
                                BoxLayout:
                                    orientation:"vertical"
                                    size_hint:(None,None)
                                    size:250,150
                                    padding:[20,0,0,20]
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)


                                    ImageButton:
                                
                                        source:'assets/computer.png'  
                                        size_hint_x:None
                                        width:70
                                        size_hint:(None,None)
                                        size:(70,70)
                                    Button:
                                        text:"DashBoard"
                                        halign: 'left'
                                        background_normal:""
                                        background_color: rgba('#010c47')
                                        background_down:'dark.png'
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)
                                        
                                                        
                                    

                                BoxLayout:
                                    orientation:"vertical"
                                    size_hint:(None,None)
                                    padding:[20,0,0,20]
                                    size:250,150
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)
                                    ImageButton:
                                
                                        source:'assets/patient.png'  
                                        size_hint:(None,None)
                                        size:(70,70)
                                        
                                    Button:
                                        text:"Patient"
                                        background_normal:""
                                        background_color: rgba('#010c47')
                                        background_down:'dark.png'
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)
                                        
                                        

                                BoxLayout:
                                    orientation:"vertical"
                                    padding:[20,0,0,20]
                                    size_hint:(None,None)
                                    size:250,150
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)
                                    
                                    ImageButton:
                                        size_hint:(None,None)
                                        size:(70,70)
                                        source:'assets/doctor.png'  
                                        
                                        
                                    Button:
                                        text:"Doctor "
                                        background_normal:""
                                        background_down:'dark.png'
                                        background_color: rgba('#010c47')
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)
                                        on_press:root.doctor_list()
                                        
                                        

                                BoxLayout:
                                    orientation:"vertical"
                                    padding:[20,0,0,20]
                                    size_hint:(None,None)
                                    size:250,150
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)
                                    ImageButton:
                                
                                        source:'assets/prescription.png'  
                                        size_hint:(None,None)
                                        size:(70,70)
                                        
                                    Button:
                                        text:"Pharmascist"
                                        background_down:'dark.png'
                                        background_normal:""
                                        background_color: rgba('#010c47')
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)

                                    


                            
                            


                                    
                                
                            BoxLayout:
                                orientation:'horizontal'
                                spacing:10
                                
                                BoxLayout:
                                    size_hint:(None,None)
                                    size:250,150
                                    padding:[20,0,0,20]
                                    orientation:"vertical"
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)
                                    ImageButton:
                                
                                        source:'assets/nurse.png'  
                                        size_hint:(None,None)
                                        size:(70,70)
                                        
                                    Button:
                                        text:"Nurse"
                                        background_down:'dark.png'
                                        background_normal:""
                                        background_color: rgba('#010c47')
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)
                                BoxLayout:
                                    size_hint:(None,None)
                                    size:250,150
                                    orientation:"vertical"
                                    padding:[20,0,0,20]
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)

                                    ImageButton:
                                
                                        source:'assets/pencil.png'  
                                        size_hint:(None,None)
                                        size:(70,70)
                                        
                                    Button:
                                        text:"Lab"
                                        background_down:'dark.png'
                                        background_normal:""
                                        background_color: rgba('#010c47')
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)

                                BoxLayout:
                                    size_hint:(None,None)
                                    size:250,150
                                    padding:[20,0,0,20]
                                    orientation:"vertical"
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)
                                    ImageButton:
                                
                                        source:'assets/clipboard.png'  
                                        size_hint:(None,None)
                                        size:(70,70)
                                                
                                    Button:
                                        text:"Monitor Hospital"
                                        background_normal:""
                                        background_down:'dark.png'
                                        background_color: rgba('#010c47')
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)

                                BoxLayout:
                                    size_hint:(None,None)
                                    size:250,150
                                    padding:[20,0,0,20]
                                    orientation:"vertical"
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)

                                    ImageButton:
                                
                                        source:'assets/gamepad.png'  
                                        size_hint:(None,None)
                                        size:(70,70)
                                        
                                    Button:
                                        text:"Settings"
                                        background_normal:""
                                        background_down:'dark.png'
                                        background_color: rgba('#010c47')
                                        font_size: 25
                                        size_hint:(None,None)
                                        size:(200,50)

    
                            BoxLayout:

                                orientation:'horizontal'
                                spacing:20

                                BoxLayout:
                                    orientation:"vertical"
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)

                                    BoxLayout:
                                        canvas:
                                            Color:
                                                rgba: rgba('#010c47')
                                            Rectangle:
                                                pos:self.pos
                                                size:self.size
                                        id:calendar
                                        
                                BoxLayout:
                                    orientation:"vertical"
                                    canvas:
                                        Color:
                                            rgba: 0, 0, 0, .9
                                        Line:
                                            width: 2.
                                            rectangle: (self.x, self.y, self.width, self.height)


                                    BoxLayout:
                                        size_hint_y:None
                                        height:40
                                        canvas:
                                            Color:
                                                rgba: rgba("#1c41fd")
                                            Rectangle:
                                                pos:self.pos
                                                size:self.size
                                                
                                        ImageButton:
                                            source:'assets/list.png'  
                                            size_hint_x:None
                                            width:70

                                        Label:
                                            text:"Notice Board"
                                            color:1,1,1,1
                                            
                                    BoxLayout:
                                        Label:
                                            text:""
                                            color:0,0,0,1
                                        ImageButton:
                                            source:'assets/pencil2.png'  
                                            size_hint_x:None
                                            width:70

                                        Label:
                                            text:"Yout appointement"
                                            color:0,0,0,1
                                        
                                        Label:
                                            text:""
                                            color:0,0,0,1
                                            


                            Button:
                                text:'Admin'
                                on_press:root.manager.current='Pharmascist'
                                size_hint:(None,None)
                                size:(100,50)
<Manage_department>:
    cols:1
    
    manage_adding:manage_adding
    BoxLayout:
        
        BoxLayout:
            
            GridLayout:
                cols :1  
                GridLayout:
                    cols :1
                    size_hint_y: 0.3
                    
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    Label:
                        text:"Manage Departments"
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:80

                    Label:
                        text:""
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:40
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0, 1
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                    
                    GridLayout:
                        cols :1
                        spacing:20
                        row_force_default:True
                        row_default_height:40
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 0, 0, 1,1 
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/list.png'  
                                size_hint:None,None
                                size:70,40
                            Button:
                                text:"Department List"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.return_departmentList()

                            Button:
                                text:"+ Add Department"
                                color:0,0,0,1
                                halign: 'left'
                                background_normal:""
                                background_color: 1,1,1,1
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.adding_deparment()
                                                               

                            Label:
                                text:"Search"
                                color:0,0,0,1
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)
                                            
                            TextInput:
                                multiline:False
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)

                        Label:
                            text:""
                            color:0,0,0,1
                            size_hint_y:None
                            font_size:40
                            height:20


                GridLayout:
                    cols:1
                    size_hint_y: 0.7
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Department"
                                font_size: 25
                                            
                            Button:
                                text:"Description"
                                font_size: 25
                                    

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:3
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        


<Add_department> :
    cols:1
    GridLayout:
        cols:2
        row_force_default:True
        row_default_height:40
        spacing:150
        padding:[0,10,100,0]
     
        
        Label:
            text:'Department Name'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_bed
            size_hint_x:None
            width:300

        Label:
            text:'Department Description'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_patient
            multiline:True
            size_hint:None,None
            size:300,150
            
        
            
    BoxLayout:
        Label:
            text:''
            color:0,0,0,1
            font_size:25
            size_hint:None,None
            size:(200,40)
        Button:
            text:'Add Department'
            size_hint:None,None
            size:(200,40)
            
    Label:
        text:''
        color:0,0,0,1
        font_size:25
        size_hint:None,None
        size:(200,40)       
                      
<Return_departmentList> :
    BoxLayout:
        BoxLayout:
            BoxLayout:
                BoxLayout:
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Department"
                                font_size: 25
                                            
                            Button:
                                text:"Description"
                                font_size: 25
                                    

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:3
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        

<Manage_doctor>:
    cols:1
    
    manage_adding:manage_adding
    BoxLayout:
        
        BoxLayout:
            
            GridLayout:
                cols :1  
                GridLayout:
                    cols :1
                    size_hint_y: 0.3
                    
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    Label:
                        text:"Manage Doctor"
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:80

                    Label:
                        text:""
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:40
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0, 1
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                    
                    GridLayout:
                        cols :1
                        spacing:20
                        row_force_default:True
                        row_default_height:40
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 0, 0, 1,1 
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/list.png'  
                                size_hint:None,None
                                size:70,40
                            Button:
                                text:"Doctor List"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.return_doctorList()

                            Button:
                                text:"+ Add Doctor"
                                color:0,0,0,1
                                halign: 'left'
                                background_normal:""
                                background_color: 1,1,1,1
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.adding_doctor()
                                                               

                            Label:
                                text:"Search"
                                color:0,0,0,1
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)
                                            
                            TextInput:
                                multiline:False
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)

                        Label:
                            text:""
                            color:0,0,0,1
                            size_hint_y:None
                            font_size:40
                            height:20


                GridLayout:
                    cols:1
                    size_hint_y: 0.7
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Doctor Name"
                                font_size: 25
                                            
                            Button:
                                text:"Department"
                                font_size: 25
                                    

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:3
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        
<Add_doctor>:
    cols:1
    
    GridLayout:
        cols:2
        row_force_default:True
        row_default_height:40
        spacing:20
        padding:[0,10,100,0]
     
        
        Label:
            text:'Name'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_bed
            size_hint_x:None
            width:300

        Label:
            text:'Email'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_patient
            multiline:True
            size_hint_x:None
            width:300

        Label:
            text:'Password'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_bed
            size_hint_x:None
            width:300
        Label:
            text:'Address'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_bed
            size_hint_x:None
            width:300

        Label:
            text:'Phone'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_bed
            size_hint_x:None
            width:300

        Label:
            text:'Department'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_bed
            size_hint_x:None
            width:300

        Label:
            text:'Profile'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:allotment_bed
            size_hint_x:None
            width:300







        
            
    BoxLayout:
        Label:
            text:''
            color:0,0,0,1
            font_size:25
            size_hint:None,None
            size:(200,40)
        Button:
            text:'Add Department'
            size_hint:None,None
            size:(200,40)
            
    Label:
        text:''
        color:0,0,0,1
        font_size:25
        size_hint:None,None
        size:(200,40)       
    

<Return_doctorList>:
    BoxLayout:
        BoxLayout:
            BoxLayout:
                BoxLayout:
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Doctor Name"
                                font_size: 25
                                            
                            Button:
                                text:"Department"
                                font_size: 25
                                    

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:3
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        


<Manage_Nurse>:
    cols:1
    
    manage_adding:manage_adding
    BoxLayout:
        
        BoxLayout:
            
            GridLayout:
                cols :1  
                GridLayout:
                    cols :1
                    size_hint_y: 0.3
                    
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    Label:
                        text:"Manage Nurse"
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:80

                    Label:
                        text:""
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:40
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0, 1
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                    
                    GridLayout:
                        cols :1
                        spacing:20
                        row_force_default:True
                        row_default_height:40
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 0, 0, 1,1 
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/list.png'  
                                size_hint:None,None
                                size:70,40
                            Button:
                                text:"Nurse List"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.return_nurseList()

                            Button:
                                text:"+ Add Nurse"
                                color:0,0,0,1
                                halign: 'left'
                                background_normal:""
                                background_color: 1,1,1,1
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.adding_nurse()
                                                               

                            Label:
                                text:"Search"
                                color:0,0,0,1
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)
                                            
                            TextInput:
                                multiline:False
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)

                        Label:
                            text:""
                            color:0,0,0,1
                            size_hint_y:None
                            font_size:40
                            height:20


                GridLayout:
                    cols:1
                    size_hint_y: 0.7
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Nurse Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25

                            Button:
                                text:"Address"
                                font_size: 25

                            Button:
                                text:"Phone"
                                font_size: 25

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        
<Add_nurse>:
    cols:1
    
    GridLayout:
        cols:2
        row_force_default:True
        row_default_height:40
        spacing:20
        padding:[0,10,100,0]
     
        
        Label:
            text:'Name'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:nurse_name
            size_hint_x:None
            width:300

        Label:
            text:'Email'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:nurse_email
            multiline:True
            size_hint_x:None
            width:300

        Label:
            text:'Password'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:nurse_password
            size_hint_x:None
            width:300
        Label:
            text:'Address'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:nurse_address
            size_hint_x:None
            width:300

        Label:
            text:'Phone'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:nurse_phone
            size_hint_x:None
            width:300


        
            
    BoxLayout:
        Label:
            text:''
            color:0,0,0,1
            font_size:25
            size_hint:None,None
            size:(200,40)
        Button:
            text:'Add Department'
            size_hint:None,None
            size:(200,40)
            
    Label:
        text:''
        color:0,0,0,1
        font_size:25
        size_hint:None,None
        size:(200,40)       
    

<Return_nurseList>:
    BoxLayout:
        BoxLayout:
            BoxLayout:
                BoxLayout:
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Nurse Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25
                                
                            Button:
                                text:"Address"
                                font_size: 25
                            Button:
                                text:"Phone"
                                font_size: 25

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        

<Manage_pharm>:
    cols:1
    
    manage_adding:manage_adding
    BoxLayout:
        
        BoxLayout:
            
            GridLayout:
                cols :1  
                GridLayout:
                    cols :1
                    size_hint_y: 0.3
                    
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    Label:
                        text:"Manage Pharmacist"
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:80

                    Label:
                        text:""
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:40
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0, 1
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                    
                    GridLayout:
                        cols :1
                        spacing:20
                        row_force_default:True
                        row_default_height:40
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 0, 0, 1,1 
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/list.png'  
                                size_hint:None,None
                                size:70,40
                            Button:
                                text:"Pharmacist List"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.return_pharmList()

                            Button:
                                text:"+ Add Pharmacist"
                                color:0,0,0,1
                                halign: 'left'
                                background_normal:""
                                background_color: 1,1,1,1
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.adding_pharm()
                                                               

                            Label:
                                text:"Search"
                                color:0,0,0,1
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)
                                            
                            TextInput:
                                multiline:False
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)

                        Label:
                            text:""
                            color:0,0,0,1
                            size_hint_y:None
                            font_size:40
                            height:20


                GridLayout:
                    cols:1
                    size_hint_y: 0.7
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Pharmacist Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25

                            Button:
                                text:"Address"
                                font_size: 25

                            Button:
                                text:"Phone"
                                font_size: 25

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        
<Add_pharm>:
    cols:1
    
    GridLayout:
        cols:2
        row_force_default:True
        row_default_height:40
        spacing:20
        padding:[0,10,100,0]
     
        
        Label:
            text:'Name'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:pharm_name
            size_hint_x:None
            width:300

        Label:
            text:'Email'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:pharm_email
            multiline:True
            size_hint_x:None
            width:300

        Label:
            text:'Password'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:pharm_password
            size_hint_x:None
            width:300
        Label:
            text:'Address'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:pharm_address
            size_hint_x:None
            width:300

        Label:
            text:'Phone'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:pharm_phone
            size_hint_x:None
            width:300


        
            
    BoxLayout:
        Label:
            text:''
            color:0,0,0,1
            font_size:25
            size_hint:None,None
            size:(200,40)
        Button:
            text:'Add Department'
            size_hint:None,None
            size:(200,40)
            
    Label:
        text:''
        color:0,0,0,1
        font_size:25
        size_hint:None,None
        size:(200,40)       
    

<Return_pharmList>:
    BoxLayout:
        BoxLayout:
            BoxLayout:
                BoxLayout:
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Pharmacist Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25
                                
                            Button:
                                text:"Address"
                                font_size: 25
                            Button:
                                text:"Phone"
                                font_size: 25
                                    
                                            

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        


    

<Manage_Lab>:
    cols:1
    
    manage_adding:manage_adding
    BoxLayout:
        
        BoxLayout:
            
            GridLayout:
                cols :1  
                GridLayout:
                    cols :1
                    size_hint_y: 0.3
                    
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    Label:
                        text:"Manage Labaratorist"
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:80

                    Label:
                        text:""
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:40
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0, 1
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                    
                    GridLayout:
                        cols :1
                        spacing:20
                        row_force_default:True
                        row_default_height:40
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 0, 0, 1,1 
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/list.png'  
                                size_hint:None,None
                                size:70,40
                            Button:
                                text:"Labaratorist List"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.return_labList()

                            Button:
                                text:"+ Add Labaratorist"
                                color:0,0,0,1
                                halign: 'left'
                                background_normal:""
                                background_color: 1,1,1,1
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.adding_lab()
                                                               

                            Label:
                                text:"Search"
                                color:0,0,0,1
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)
                                            
                            TextInput:
                                multiline:False
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)

                        Label:
                            text:""
                            color:0,0,0,1
                            size_hint_y:None
                            font_size:40
                            height:20


                GridLayout:
                    cols:1
                    size_hint_y: 0.7
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Labaratorist Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25

                            Button:
                                text:"Address"
                                font_size: 25

                            Button:
                                text:"Phone"
                                font_size: 25

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        
<Add_lab>:
    cols:1
    
    GridLayout:
        cols:2
        row_force_default:True
        row_default_height:40
        spacing:20
        padding:[0,10,100,0]
     
        
        Label:
            text:'Name'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:lab_name
            size_hint_x:None
            width:300

        Label:
            text:'Email'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:lab_email
            multiline:True
            size_hint_x:None
            width:300

        Label:
            text:'Password'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:lab_password
            size_hint_x:None
            width:300
        Label:
            text:'Address'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:lab_address
            size_hint_x:None
            width:300

        Label:
            text:'Phone'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:lab_phone
            size_hint_x:None
            width:300


        
            
    BoxLayout:
        Label:
            text:''
            color:0,0,0,1
            font_size:25
            size_hint:None,None
            size:(200,40)
        Button:
            text:'Add Labaratorist'
            size_hint:None,None
            size:(200,40)
            
    Label:
        text:''
        color:0,0,0,1
        font_size:25
        size_hint:None,None
        size:(200,40)       
    

<Return_labList>:
    BoxLayout:
        BoxLayout:
            BoxLayout:
                BoxLayout:
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Labaratorist Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25
                                
                            Button:
                                text:"Address"
                                font_size: 25
                            Button:
                                text:"Phone"
                                font_size: 25
                                    
                                            

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        


    


<Manage_Accountant>:
    cols:1
    
    manage_adding:manage_adding
    BoxLayout:
        
        BoxLayout:
            
            GridLayout:
                cols :1  
                GridLayout:
                    cols :1
                    size_hint_y: 0.3
                    
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    Label:
                        text:"Manage Accountant"
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:80

                    Label:
                        text:""
                        color:0,0,0,1
                        size_hint_y:None
                        font_size:40
                        height:40
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0, 1
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                    
                    GridLayout:
                        cols :1
                        spacing:20
                        row_force_default:True
                        row_default_height:40
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 0, 0, 1,1 
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'assets/list.png'  
                                size_hint:None,None
                                size:70,40
                            Button:
                                text:"Accountant List"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.return_accountantList()

                            Button:
                                text:"+ Add Accountant"
                                color:0,0,0,1
                                halign: 'left'
                                background_normal:""
                                background_color: 1,1,1,1
                                background_down:'dark.png'
                                font_size: 25
                                size_hint:None,None
                                size:200,40
                                on_press:root.adding_accountant()
                                                               

                            Label:
                                text:"Search"
                                color:0,0,0,1
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)
                                            
                            TextInput:
                                multiline:False
                                font_size: 25
                                size_hint:None,None
                                size:(200,40)

                        Label:
                            text:""
                            color:0,0,0,1
                            size_hint_y:None
                            font_size:40
                            height:20


                GridLayout:
                    cols:1
                    size_hint_y: 0.7
                    canvas:
                        Color:
                            rgba: 1,1,1,.8
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Accountant's Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25

                            Button:
                                text:"Address"
                                font_size: 25

                            Button:
                                text:"Phone"
                                font_size: 25

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        
<Add_accountant>:
    cols:1
    
    GridLayout:
        cols:2
        row_force_default:True
        row_default_height:40
        spacing:20
        padding:[0,10,100,0]
     
        
        Label:
            text:'Name'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:accountant_name
            size_hint_x:None
            width:300

        Label:
            text:'Email'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:accountant_email
            multiline:True
            size_hint_x:None
            width:300

        Label:
            text:'Password'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:accountant_password
            size_hint_x:None
            width:300
        Label:
            text:'Address'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:accountant_address
            size_hint_x:None
            width:300

        Label:
            text:'Phone'
            color:0,0,0,1
            font_size:25
        TextInput:
            id:accountant_phone
            size_hint_x:None
            width:300


        
            
    BoxLayout:
        Label:
            text:''
            color:0,0,0,1
            font_size:25
            size_hint:None,None
            size:(200,40)
        Button:
            text:'Add Accountant'
            size_hint:None,None
            size:(200,40)
            
    Label:
        text:''
        color:0,0,0,1
        font_size:25
        size_hint:None,None
        size:(200,40)       
    

<Return_accountantList>:
    BoxLayout:
        BoxLayout:
            BoxLayout:
                BoxLayout:
                    BoxLayout:
                        id:manage_adding
                        orientation:'vertical'
                        canvas.before:
                                
                            Color:
                                rgba: 0, 0, 0,1 
                            Line:
                                width:1
                                rectangle: (self.x,self.y-5, self.width, self.height)
                                                     

                
                            
                        
                            

                        BoxLayout:
                            size_hint_y:None
                            height:40
                            Button:
                                text:"No"
                                font_size: 25
                                
                            Button:
                                text:"Accountant Name"
                                font_size: 25
                                            
                            Button:
                                text:"Email"
                                font_size: 25
                                
                            Button:
                                text:"Address"
                                font_size: 25
                            Button:
                                text:"Phone"
                                font_size: 25
                                    
                                            

                        BoxLayout:
                           
                            RecycleView:
                                bar_width: 10
                                bar_color: 1, 0, 0, 1   # red
                                bar_inactive_color: 0, 0, 1, 1   # blue
                                effect_cls: "ScrollEffect"
                                scroll_type: ['bars']
                                viewclass: 'SelectableButton'
                                data:[{'text': str(x)} for x in range(20)]
                                SelectableRecycleGridLayout:
                                    cols:5
                                    default_size: None, dp(56)
                                    default_size_hint:1, None
                                    size_hint_y: None
                                    height: self.minimum_height
                                    orientation: 'vertical'
                                    multiselect: True
                                    touch_multiselect: True
                        Label:
                            text:""
                            color:0,0,0,1
                            font_size: 25
                            size_hint:None,None
                            size:(200,40)
                        


    

    
