#:import rgba kivy.utils.rgba
#: include dokte.kv

<MyScreenManager>:

    id: screen_manager

    screen_login: login
    screen_doctor: doctor
    screen_accountant:accountant


    ScreenLogin:
        id: login
        name: 'Login'
        manager: screen_manager

    ScreenDoctor:
        id: doctor
        name: 'Doctor'
        manager: screen_manager

    ScreenAdmin:
        id: accountant
        name: 'Admin'
        manager: screen_manager









 

                        
<ScreenLogin>:
    symptom_box:symptom_box
    diagnosis_box:diagnosis_box
    manage_patient:manage_patient
    symptomsearch_id:symptomsearch_id
    diagnosearch_id:diagnosearch_id
    choose_doc:choose_doc

    tp:tp

    
    BoxLayout:
        orientation: 'vertical'
        padding: root.width*0.005,root.height*0.005
        canvas:
            Color:
                rgba:1,1,1,1
            Rectangle:
                pos: self.pos
                size: self.size
        ActionBar:
            pos_hint: {'top':1}
            ActionView:
                use_separator: True
                ActionPrevious:
                    title: 'Hospital Management System'
                    with_previous: False
                ActionButton:
                    text: "Accountant's Panel"
                    background_down:'1,0,1,0'
                    
                ActionGroup:
                    text: " Account"
                    mode: 'spinner'
                    ActionButton:
                        text: 'Profile'
                        on_press:root.profile()
                    ActionButton:
                        text: 'Log Out'
                        on_press:root.manager.current='Login'


                
        BoxLayout:
            orientation:'horizontal'
            spacing:2
                
            BoxLayout:
                orientation:'vertical'
                size_hint:(None,None)
                size:300, self.parent.height  
                spacing:20
                
                BoxLayout:
                    orientation:'vertical'
                    
                    canvas:
                        Color:
                            rgba: rgba('#010c47')
                        Rectangle:
                            pos:self.pos
                            size:self.size
                    
                    ImageButton:
                                
                        source:'hsign.png'  
                        size_hint:(None,None)
                        size:(200,80)
                        
                    Label:
                        text:""
                        size_hint_y:None
                        height:15
                        canvas.before:
                                
                            Color:
                                rgba: 1, 1, 1, .2
                            Line:
                                width:1
                                rectangle: (self.x,self.y+10, self.width, 0)
                                                     

                            
                        

                    GridLayout:
                        cols :1
                        spacing:20
                        row_force_default: True
                        row_default_height: 40
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'computer.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"DashBoard"
                                halign: 'left'
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint_x:None
                                width:200
                                on_press:root.account_dashboard()

                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'patient.png'  
                                size_hint_x:None
                                width:70
                            Button:
                                text:"Take Payment "
                                background_normal:""
                                background_color: rgba('#010c47')
                                background_down:'dark.png'
                                font_size: 25
                                size_hint_x:None
                                width:200
                        BoxLayout:
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'pencil.png'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"View Payment "
                                background_normal:""
                                background_down:'dark.png'
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint_x:None
                                width:200

                        

                       

                       

                        
                        BoxLayout:
                            
                            canvas.before:
                                
                                Color:
                                    rgba: 1, 1, 1, .2
                                Line:
                                    width:1
                                    rectangle: (self.x,self.y-5, self.width, 0)
                                                     

                            ImageButton:
                                
                                source:'boy.png'  
                                size_hint_x:None
                                width:70
                                
                            Button:
                                text:"Profile"
                                background_normal:""
                                background_down:'dark.png'
                                background_color: rgba('#010c47')
                                font_size: 25
                                size_hint_x:None
                                width:200
                                on_press:root.profile()

                        




       

  
                            
                                          
##########         """ dynamic part begins here"""    ######################

                                
         
            BoxLayout:
                ScrollView:
                    size:self.size
                    bar_width: 10
                    bar_color: 1, 0, 0, 1   # red
                    bar_inactive_color: 0, 0, 1, 1   # blue
                    effect_cls: "ScrollEffect"
                    scroll_type: ['bars']
                    
                    GridLayout:
                        cols:1
                        id: view
                        size_hint_y: 1
                        padding:self.height*0.01, self.width*0.01
                        
                        BoxLayout:
                            size_hint_y: None
                            height:self.minimum_height
                            spacing:30
                            orientation: 'vertical'
                            canvas:
                                Color:
                                    rgba: 0, 0, 0, .3
                                Line:
                                    width: 1.
                                    rectangle: (self.x, self.y, self.width, self.height)
                            BoxLayout:
                                id:manage_patient
                                orientation: 'vertical'
                                spacing:30
                                padding:self.height*0.02, self.width*0.02
                                size_hint_y: None
                                height:self.minimum_height

                                

                                                                    
                                        
                                        
                                BoxLayout:
                                    orientation:'horizontal'
                                    size_hint_y: None
                                    height:self.minimum_height
                                    spacing:40
                                    
                                    GridLayout:
                                        cols:2

                                        spacing:20

                                        
                                        Label:
                                            
                                            text:'unique Id:'
                                            font_size: 20
                                            color:0,0,0,1
                                            size_hint_y:None
                                            height:40



                                        TextInput:
                                            size_hint:None,None
                                            size:(200,40)
                                            multiline:False
                                            font_size: 25
                                            


                                            
                                            
                                        Label:
                                            text:'Name:'
                                            font_size: 25
                                            color:0,0,0,1
                                            size_hint_y: None
                                            height:40
                                            
                                            



                                        TextInput:
                                            multiline:False
                                            font_size: 25
                                            size_hint:None,None
                                            size:(200,40)


                                    
                                    GridLayout:
                                        cols:2
                                        size_hint_y: None
                                        height:self.minimum_height
                                        spacing:20


                                        Label:
                                            text:'Gender'
                                            font_size: 25
                                            color:0,0,0,1
                                            size_hint_y: None
                                            height:40



                                        TextInput:
                                            multiline:False
                                            font_size: 25
                                            size_hint:None,None
                                            size:(200,40)

                                        Label:
                                            text:'Age'
                                            font_size: 25
                                            color:0,0,0,1
                                            size_hint_y:None
                                            height:40



                                        TextInput:
                                            multiline:False
                                            font_size: 25
                                            size_hint:None,None
                                            size:(70,40)
                                                
                                        
                               
                                    
                                    GridLayout:
                                        cols:2
                                        size_hint_y: None
                                        height:self.minimum_height
                                        spacing:20
                                        
                                        Label:
                                            text:'Doctor'
                                            font_size: 25
                                            color:0,0,0,1                                       
                                            height:40





                                        TextInput:
                                            multiline:False
                                            font_size: 25
                                            size_hint_y: None
                                            height:35


                                            

                                        Label:
                                            text:'Blood Group'
                                            font_size: 25
                                            color:0,0,0,1
                                            size_hint_y: None
                                            height:40





                                        TextInput:
                                            multiline:False
                                            font_size: 25 
                                            size_hint_y: None
                                            height:35


                                    
                                   
                        Label:
                            text:''
                            font_size: 25
                            color:0,0,0,1
                            size_hint_y: None
                            height:20

                        BoxLayout:
                            orientation:'horizontal'
                            size_hint_y: None
                            height:self.minimum_height
                            
                            BoxLayout:
                                orientation:'vertical'
                                size_hint_y: None
                                height:self.minimum_height
                                padding: self.height*0.01, self.width*0.01
                                canvas:
                                    Color:
                                        rgba: 0, 0, 0, .3
                                    Line:
                                        width: 1
                                        rectangle: (self.x, self.y, self.width, self.height)
                           

                                
                                TabbedPanel:
                                    id:tp
                                    height:self.minimum_height
                                    spacing:30
                                    size_hint: 1,None
                                    do_default_tab: False
                                    tab_width: None

                                    
                                    TabbedPanelItem:
                                        text: "Prev_history"
                                        width: '200dp'
                                        size_hint_x: None
                                        Label:
                                            text:' VIew history'
                                            color:0,0,0,1

                                    TabbedPanelItem:
                                        text:"Health Details"
                                        width: '200dp'
                                        size_hint_x: None
                                        BoxLayout:
                                            id:btab
                                            orientation:'horizontal'
                                            size_hint_y:None
                                            height:'400dp'
                                            padding:['20dp','50dp','20dp','50dp']
                                            spacing:'20dp'
                                            canvas:
                                                Color:
                                                    rgba: 0, 0, 0, .3
                                                Line:
                                                    width: 1
                                                    rectangle: (self.x, self.y, self.width, self.height)

                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint_x:btab.size[0]*0.25
                                                padding:['0dp','70dp','10dp',0]

                                                canvas:
                                                    Color:
                                                        rgba: 0, 0, 0, .3
                                                    Line:
                                                        width: 2
                                                        rectangle: (self.x, self.y, self.width, self.height)

                                                GridLayout:
                                                    cols:2
                                                    row_force_default:True
                                                    row_default_height:'40dp'
                                                    spacing:'10dp'

                                                    Label:
                                                        text:'Weight(KG)'
                                                        color:0,0,0,1
                                                    TextInput:
                                                        id: height_id

                                                    Label:
                                                        text:'Height(CM)'
                                                        color:0,0,0,1
                                                    TextInput:
                                                        id: height_id

                                                    Label:
                                                        text:'Bp   '
                                                        color:0,0,0,1

                                                    TextInput:
                                                        id: height_id





                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint_x:btab.size[0]*0.75
                                                padding:['0dp',0,'20dp', 0]
                                                canvas:
                                                    Color:
                                                        rgba: 0, 0, 0, .3
                                                    Line:
                                                        width: 2
                                                        rectangle: (self.x, self.y, self.width, self.height)


                                                GridLayout:
                                                    id:spec_detail
                                                    cols:3
                                                    row_force_default:True
                                                    row_default_height:'40dp'

                                                    spacing:'10dp'


                                                    Label:
                                                        text:'[b]No.[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20
                                                        markup:True


                                                    Label:
                                                        text:'[b]Field Name[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40
                                                        markup:True


                                                    Label:
                                                        text:'[b]Field Answer[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40
                                                        markup:True


                                                    Label:
                                                        text:'1.'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20

                                                    Label:
                                                        text:'Are You Taking any Medication?'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    TextInput:
                                                        hint_text:'Field Answer'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    Label:
                                                        text:'2.'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20



                                                    Label:
                                                        text:'Have You Undergone any tests?'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    TextInput:
                                                        hint_text:'Field Answer'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40


                                                    Label:
                                                        text:'3.'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20


                                                    Label:
                                                        text:'DO your Drink Alcohol'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    TextInput:
                                                        hint_text:'Field Answer'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    Label:
                                                        text:'4.'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20


                                                    Label:
                                                        text:'DO you smoke'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    TextInput:
                                                        hint_text:'Field Answer'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    Label:
                                                        text:'5.'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20


                                                    Label:
                                                        text:'Total Living Children'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40

                                                    TextInput:
                                                        hint_text:'Field Answer'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40


                                    TabbedPanelItem:
                                        text:'Documents'
                                        width: '200dp'
                                        size_hint_x: None
                                        BoxLayout:
                                            id:btab1
                                            orientation:'horizontal'
                                            size_hint_y:None
                                            height:'400dp'
                                            padding:['20dp','50dp','20dp','0dp']
                                            spacing:'20dp'
                                            canvas:
                                                Color:
                                                    rgba: 0, 0, 0, .3
                                                Line:
                                                    width: 1
                                                    rectangle: (self.x, self.y, self.width, self.height)

                                            BoxLayout:
                                                id:image_box
                                                orientation:'vertical'
                                                size_hint_x:btab1.size[0]*0.25
                                                padding:['0dp','0dp','10dp','10dp']
                                                spacing:'20dp'

                                                ImageButton:
                                                    id: choose_doc
                                                    size_hint:None,None
                                                    source:'doc.jpg'
                                                    height:'230dp'
                                                    text:'select image'
                                                    on_press:root.choose_file()
                                                    width:image_box.size[0]
                                                    canvas:
                                                        Color:
                                                            rgba: 0, 0, 0, .3
                                                        Line:
                                                            width: 2
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                GridLayout:
                                                    cols:2
                                                    row_force_default:True
                                                    row_default_height:'30dp'
                                                    Label:
                                                        text:'Rename'
                                                        color:0,0,0,1
                                                    TextInput:
                                                        hint_text:'Enter'

                                                Button:
                                                    text: 'Add Document'

                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint_x:btab1.size[0]*0.75
                                                padding:['0dp',0,'20dp', 0]
                                                canvas:
                                                    Color:
                                                        rgba: 0, 0, 0, .3
                                                    Line:
                                                        width: 2
                                                        rectangle: (self.x, self.y, self.width, self.height)


                                                GridLayout:
                                                    id:spec_detail
                                                    cols:3
                                                    row_force_default:True
                                                    row_default_height:'40dp'

                                                    spacing:'10dp'


                                                    Label:
                                                        text:'[b]No.[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20
                                                        markup:True


                                                    Label:
                                                        text:'[b]Field Name[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40
                                                        markup:True


                                                    Label:
                                                        text:'[b]Image[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40
                                                        markup:True


##############################################################################################################################################################


                                    TabbedPanelItem:
                                        text:"Prescription"
                                        width: '200dp'
                                        size_hint_x: None
                                        ScrollView:
                                            size_hint_y:None
                                            height:'400dp'
                                            bar_width: 10
                                            bar_color: 1, 0, 0, 1   # red
                                            bar_inactive_color: 0, 0, 1, 1   # blue
                                            effect_cls: "ScrollEffect"
                                            scroll_type: ['bars']
                                            canvas:
                                                Color:
                                                    rgba: 0, 0, 0, 0.3
                                                Line:
                                                    width: 1
                                                    rectangle: (self.x, self.y, self.width, self.height)
                                            BoxLayout:
                                                orientation:'vertical'
                                                padding:['20dp','30dp','20dp','0dp']
                                                #spacing:'20dp'
                                                size_hint_y:None
                                                height:self.minimum_height

                                                canvas:
                                                    Color:
                                                        rgba: 0, 0, 0, .3
                                                    Line:
                                                        width: 1
                                                        rectangle: (self.x, self.y, self.width, self.height)

                                                BoxLayout:
                                                    id:tab_presc
                                                    orientation:'horizontal'
                                                    size_hint_y:None
                                                    padding:['0dp','20dp','10dp','10dp']
                                                    height:self.minimum_height


                                                    BoxLayout:
                                                        orientation:'vertical'
                                                        size_hint_x:tab_presc.size[0]*0.25
                                                        padding:['0dp','0dp','10dp','10dp']
                                                        spacing:'20dp'
                                                        size_hint_y:None
                                                        height:self.minimum_height



                                                        TextInput:
                                                            id: symptomsearch_id
                                                            hint_text:'Search Symptoms'
                                                            size_hint_y:None
                                                            height:'30dp'
                                                            halign:'center'
                                                            valign:'middle'
                                                            on_text:root.on_type_validate()

                                                        ScrollView:
                                                            id:symptom_box
                                                            bar_width: 10
                                                            bar_color: 1, 0, 0, 1   # red
                                                            bar_inactive_color: 0, 0, 1, 1   # blue
                                                            effect_cls: "ScrollEffect"
                                                            scroll_type: ['bars']
                                                            padding:['0dp','0dp','10dp','0dp']
                                                            size_hint_y:None
                                                            height:'200dp'
                                                            canvas:
                                                                Color:
                                                                    rgba: 0, 0, 0, .3
                                                                Line:
                                                                    width: 1.5
                                                                    rectangle: (self.x, self.y, self.width, self.height)
                                                            Label:
                                                                text:'cool staff'
                                                                size_hint_:None
                                                                height:'150dp'


                                                        Button:
                                                            text: 'Get Diagnosis'
                                                            size_hint_y:None
                                                            height:'40dp'
                                                            on_press: root.getcheckboxes_active()

                                                    BoxLayout:
                                                        orientation:'vertical'
                                                        size_hint_x:tab_presc.size[0]*0.25
                                                        padding:['0dp','0dp','10dp','10dp']
                                                        spacing:'20dp'
                                                        size_hint_y:None
                                                        height:self.minimum_height

                                                        TextInput:
                                                            id:diagnosearch_id
                                                            hint_text:'Search Diagnosis'
                                                            size_hint_y:None
                                                            height:'30dp'
                                                            halign:'center'
                                                            valign:'middle'
                                                            on_text: root.on_type_validate_diag()

                                                        ScrollView:
                                                            id:diagnosis_box
                                                            bar_width: 10
                                                            bar_color: 1, 0, 0, 1   # red
                                                            bar_inactive_color: 0, 0, 1, 1   # blue
                                                            effect_cls: "ScrollEffect"
                                                            scroll_type: ['bars']
                                                            size_hint_y:None
                                                            height:'200dp'
                                                            padding:['0dp','0dp','10dp','0dp']
                                                            canvas:
                                                                Color:
                                                                    rgba: 0, 0, 0, .3
                                                                Line:
                                                                    width: 1.5
                                                                    rectangle: (self.x, self.y, self.width, self.height)

                                                        Button:
                                                            text: 'Get Medicine'
                                                            size_hint_y:None
                                                            height:'40dp'

                                                    BoxLayout:
                                                        orientation:'vertical'
                                                        size_hint_x:tab_presc.size[0]*0.25
                                                        padding:['0dp','0dp','10dp','10dp']
                                                        spacing:'20dp'
                                                        size_hint_y:None
                                                        height:self.minimum_height

                                                        TextInput:
                                                            hint_text:'Search Medicine'
                                                            size_hint_y:None
                                                            height:'30dp'
                                                            halign:'center'
                                                            valign:'middle'

                                                        BoxLayout:
                                                            id:medicine_box
                                                            size_hint_y:None
                                                            height:'200dp'
                                                            canvas:
                                                                Color:
                                                                    rgba: 0, 0, 0, .3
                                                                Line:
                                                                    width: 1
                                                                    rectangle: (self.x, self.y, self.width, self.height)

                                                        Button:
                                                            text: 'Add Prescription'
                                                            size_hint_y:None
                                                            height:'40dp'
                                                    BoxLayout:
                                                        orientation:'vertical'
                                                        size_hint_x:tab_presc.size[0]*0.25
                                                        padding:['0dp','0dp','10dp','10dp']
                                                        spacing:'20dp'
                                                        size_hint_y:None
                                                        height:self.minimum_height

                                                        Label:
                                                            text:'Note For Doctors Only'
                                                            size_hint_y:None
                                                            height:'30dp'
                                                            color:0,0,0,1

                                                        TextInput:
                                                            id:note_box
                                                            size_hint_y:None
                                                            height:'200dp'
                                                            multiline: True
                                                            canvas:
                                                                Color:
                                                                    rgba: 0, 0, 0, .3
                                                                Line:
                                                                    width: 1
                                                                    rectangle: (self.x, self.y, self.width, self.height)

                                                        Button:
                                                            text: 'Add note'
                                                            size_hint_y:None
                                                            height:'40dp'
                                                BoxLayout:
                                                    orientation:'vertical'
                                                    size_hint_y:None
                                                    height:self.minimum_height
                                                    padding:['0dp','10dp','0dp','20dp']

                                                    GridLayout:
                                                        row_force_default:True
                                                        row_force_height:'40dp'
                                                        size_hint_y:None
                                                        height:'40dp'


                                                        cols:5
                                                        Label:
                                                            text:'No.'
                                                            color:0,0,0,1

                                                        Label:
                                                            text:'Medicine'
                                                            color:0,0,0,1

                                                        Label:
                                                            text:'Dosage'
                                                            color:0,0,0,1
                                                        Label:
                                                            text:'Dosage Note'
                                                            color:0,0,0,1

                                                        Label:
                                                            text:'Quantity'
                                                            color:0,0,0,1
                                                    BoxLayout:

                                                        size_hint_y:None
                                                        spacing:0
                                                        height:'200dp'

                                                        RecycleView:
                                                            bar_width: 10
                                                            bar_color: 1, 0, 0, 1   # red
                                                            bar_inactive_color: 0, 0, 1, 1   # blue
                                                            #effect_cls: "ScrollEffect"
                                                            scroll_type: ['bars']
                                                            viewclass: 'SelectableButton_presc'
                                                            data:[{'text': str(x)} for x in range(30)]
                                                            SelectableRecycleGridLayout:
                                                                key_selection: 'selectable'
                                                                #row_force_default:True
                                                                #row_force_height:'40dp'
                                                                cols:5
                                                                default_size: None, dp(56)
                                                                default_size_hint:1, None
                                                                size_hint_y: None
                                                                height: self.minimum_height
                                                                orientation: 'vertical'
                                                                multiselect: True
                                                                touch_multiselect: True





                                    TabbedPanelItem:
                                        text:'Lab Test'
                                        width: '200dp'
                                        size_hint_x: None
                                        BoxLayout:
                                            id:btab2
                                            orientation:'horizontal'
                                            size_hint_y:None
                                            height:'400dp'
                                            padding:['20dp','50dp','20dp','0dp']
                                            spacing:'20dp'
                                            canvas:
                                                Color:
                                                    rgba: 0, 0, 0, .3
                                                Line:
                                                    width: 1
                                                    rectangle: (self.x, self.y, self.width, self.height)




                                            BoxLayout:
                                                id:test_box
                                                orientation:'vertical'
                                                size_hint_x:btab2.size[0]*0.45
                                                padding:['0dp','0dp','10dp','10dp']
                                                spacing:'20dp'

                                                GridLayout:
                                                    cols:2
                                                    row_force_default:True
                                                    row_default_height:'30dp'
                                                    Label:
                                                        text:'Select lab test Type'
                                                        color:0,0,0,1
                                                    TextInput:
                                                        hint_text:'Select'

                                                BoxLayout:
                                                    size_hint:None,None
                                                    height:'230dp'
                                                    width:test_box.size[0]
                                                    canvas:
                                                        Color:
                                                            rgba: 0, 0, 0, .3
                                                        Line:
                                                            width: 2
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                    GridLayout:
                                                        cols:1
                                                        Label:
                                                            text:'Select Subtype'
                                                            size_hint_y:'30dp'
                                                            color:0,0,0,1


                                                    ScrollView:
                                                        id:scrol_subtypes
                                                        GridLayout:
                                                            id:subtype_list




                                                Button:
                                                    text: 'Add test'

                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint_x:btab2.size[0]*0.55
                                                padding:['0dp',0,'20dp', 0]
                                                canvas:
                                                    Color:
                                                        rgba: 0, 0, 0, .3
                                                    Line:
                                                        width: 2
                                                        rectangle: (self.x, self.y, self.width, self.height)


                                                GridLayout:
                                                    id:spec_detail
                                                    cols:4
                                                    row_force_default:True
                                                    row_default_height:'40dp'

                                                    spacing:'10dp'

                                                    Label:
                                                        text:'[b]No.[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.10
                                                        markup:True

                                                    Label:
                                                        text:'[b]Labtest Name.[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.20
                                                        markup:True


                                                    Label:
                                                        text:'[b]SUbTest Name[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40
                                                        markup:True


                                                    Label:
                                                        text:'[b]Charges[/b]'
                                                        color:0,0,0,1
                                                        size_hint_x:spec_detail.size[0]*0.40
                                                        markup:True


<SelectableButton_presc>:
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (1, 1, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<CustomWidthTabb@TabbedPanelItem>:
    width: self.texture_size[0]
    size_hint_x: None
                                
        
<Manage_Profile>:
    
    GridLayout:
        cols:1
        
        BoxLayout:
            orientation:'vertical'
            canvas:
                Color:
                    rgba: 1,1,1,.8
                Rectangle:
                    pos:self.pos
                    size:self.size
            
            
            BoxLayout:
                
                BoxLayout:
                    
                    GridLayout:
                        cols :1  
                        GridLayout:
                            cols :1
                            size_hint_y:dp(0.5)
                            
                           
                            
                            Label:
                                text:"Manage Profile"
                                color:0,0,0,1
                                size_hint_y:None
                                font_size:40
                                height:60

                            Label:
                                text:""
                                color:0,0,0,1
                                size_hint_y:None
                                font_size:40
                                height:20
                                canvas.before:
                                        
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        width:1
                                        rectangle: (self.x,self.y+20, self.width, 0)
                            
                            GridLayout:
                                cols :1
                                spacing:20
                                row_force_default:True
                                row_default_height:40
                                padding:[50,10,50,0]
                                


                                BoxLayout:
                                    spacing:10
                                    
                                    ImageButton:
                                        
                                        source:'boy.png'  
                                        size_hint:None,None
                                        size:70,40
                                    Button:
                                        text:"Manage profile"
                                        halign: 'left'
                                        color:0,0,0,1
                                        background_normal:""
                                        background_down:'dark.png'
                                        font_size: 25
                                        size_hint:None,None
                                        size:200,40
                                        
                                    Button:
                                        text:""
                                        halign: 'left'
                                        background_normal:""
                                        background_color: rgba('#010c47')
                                        background_down:'dark.png'
                                        font_size: 25
                                BoxLayout:
                                    orientation:'vertical'
                                    padding:[0,10,30,0]
                                    canvas.before:
                                        Color:
                                            rgba:0,0,0,1
                                        Line:
                                            width:1
                                            rectangle:(self.x,self.y-195, self.width,self.height+195 )
                            
                                   
                                    GridLayout:
                                        spacing:10
                                        cols:2
                                        
                                                
                                        Label:
                                            text:"Name"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_name
                                            size_hint:None,None
                                            size:400,40


                                                
                                        Label:
                                            text:"Email"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_email
                                            size_hint:None,None
                                            size:400,40


                                                
                                        Label:
                                            text:"Address"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_address
                                            size_hint:None,None
                                            size:400,40

                                                
                                        Label:
                                            text:"Phone"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_phone
                                            size_hint:None,None
                                            size:400,40
                                    
                                    
                                       
                                        Label:
                                            text:""
                                            color:0,0,0,1
                                            size_hint:None,None
                                            size:(100,40)
                                            
                                    
                                        Button:
                                            text:'Update Profile'
                                            size_hint:None,None
                                            size:(200,40)
                                    
                                                                     


                                        

                                

                        ScrollView:
                            
                            bar_width: 10
                            bar_color: 1, 0, 0, 1   # red
                            bar_inactive_color: 0, 0, 1, 1   # blue
                            effect_cls: "ScrollEffect"
                            scroll_type: ['bars']
                            padding:[50,10,50,0]
                            BoxLayout:
                                orientation:'vertical'
                                BoxLayout:
                                    spacing:10
                                    
                                    ImageButton:
                                        
                                        source:'padlock.png'  
                                        size_hint:None,None
                                        size:70,40
                                    Button:
                                        text:"Change Password"
                                        halign: 'left'
                                        color:0,0,0,1
                                        background_normal:""
                                        background_down:'dark.png'
                                        font_size: 25
                                        size_hint:None,None
                                        size:200,40
                                        
                                    Button:
                                        text:""
                                        halign: 'left'
                                        background_normal:""
                                        background_color: rgba('#010c47')
                                        background_down:'dark.png'
                                        font_size: 25
                                        size_hint_y:None
                                        height:30
                                BoxLayout:
                                    orientation:'vertical'
                                    padding:[0,10,30,0]
                                    canvas.before:
                                        Color:
                                            rgba:0,0,0,1
                                        Line:
                                            width:1
                                            rectangle:(self.x,self.y, self.width,self.height )
                            
                                    GridLayout:
                                        
                                        spacing:10
                                        cols:2
                                        row_force_default:True
                                        row_default_height:40
                                                
                                        Label:
                                            text:"Name"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_name
                                            size_hint:None,None
                                            size:400,40


                                                
                                        Label:
                                            text:"Password"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_password
                                            size_hint:None,None
                                            size:400,40


                                                
                                        Label:
                                            text:"New password"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_newpassword
                                            size_hint:None,None
                                            size:400,40

                                                
                                        Label:
                                            text:"Confirm New password"
                                            color:0,0,0,1
                                            

                                        TextInput:
                                            multiline:False
                                            id:profile_confirmpassword
                                            size_hint:None,None
                                            size:400,40
                                                                     
                                    BoxLayout:
                                        Label:
                                            text:""
                                            color:0,0,0,1
                                            size_hint:None,None
                                            size:(200,40)
                                        
                                
                                        Button:
                                            text:'Update Password'
                                            size_hint:None,None
                                            size:(200,25)

<Add_prescription>:
    cols:1
    BoxLayout:
        BoxLayout:
            orientation:"vertical"
            BoxLayout:
                orientation:"vertical"
                GridLayout:
                    cols:2
                    row_force_default:True
                    row_default_height:40
                    spacing:20
                    padding:[0,20,100,0]
                  
                    
                    Label:
                        text:'Doctor'
                        color:0,0,0,1
                        font_size:20
                    TextInput:
                        id:appoinment_doctor
                        size_hint_x:None
                        width:700

                    Label:
                        text:'Patient'
                        color:0,0,0,1
                        font_size:20
                    TextInput:
                        id:prescription_patient
                        multiline:False
                        size_hint_x:None
                        width:700
                        
                    Label:
                        text:'Case History'
                        color:0,0,0,1
                        font_size:20
                    TextInput:
                        id:prescription_history
                        multiline:True
                        size_hint:None,None
                        size:(700,50)

                    Label:
                        text:'Medication'
                        color:0,0,0,1
                        font_size:20
                    TextInput:
                        id:prescription_med
                        multiline:False
                        size_hint_x:None
                        width:700

                    
                    Label:
                        text:'Medication from \n pharmacist'
                        color:0,0,0,1
                        font_size:20
                    TextInput:
                        id:prescription_pharm
                        multiline:True
                        size_hint:None,None
                        size:(700,50)

                    Label:
                        text:'Description'
                        color:0,0,0,1
                        font_size:20
                    TextInput:
                        id:prescription_med
                        multiline:False
                        size_hint:None,None
                        size:(700,50)

                    Label:
                        text:'Date'
                        color:0,0,0,1
                        font_size:20
                    TextInput:
                        id:prescription_date
                        multiline:False
                        size_hint:None,None
                        size:(700,50)
             
             




    BoxLayout:
        Label:
            text:''
            color:0,0,0,1
            font_size:20
            size_hint:None,None
            size:(200,40)
        
        Button:
            text:'Add Prescription'
            size_hint:None,None
            size:(200,40)

    

                                    
                                        


